Feature/http client via messagingservice
test-editor/web-workspace-navigator pull request #67
Opened 2018-04-23 07:16 UTC by gunther-bachmann

2018-04-23 08:39 UTC, jjelschen requested changes

2018-04-23 08:39 UTC, jjelschen commented on integration/e2e/app.e2e-spec.ts
> +         if (element) { \
shouldn't the test fail otherwise? Or is the absence of 'new-file' somehow expected?

2018-04-23 08:39 UTC, jjelschen commented on package.json
> +    "webdriver-manager": "^12.0.6",
That's probably only necessary because I messed up the integration test setup sometime earlier, to work around an issue we had with the integration tests on Travis, which, when run in parallel for different browsers, ran into GitHub's rate limit (because the Gecko driver is downloaded from GitHub…). I partly reverted those changes on [this branch](https://github.com/test-editor/web-workspace-navigator/tree/fix/revert-webdriver-move); not sure whether we should use that, or just introduce the webdriver-manager dependency in the parent directory, as you have.

2018-04-23 08:39 UTC, jjelschen commented on src/lib/src/component/tree-viewer/new-element.component.spec.ts
> +import { async, TestBed, ComponentFixture, tick } from '@angular/core/testing';
I don't think 'tick' is actually used anywhere (since you do not also import its prerequisite, 'fakeAsync')

2018-04-23 08:39 UTC, jjelschen commented on src/lib/src/component/tree-viewer/tree-viewer.component.spec.ts
> +import { async, ComponentFixture, TestBed, inject, fakeAsync } from '@angular/core/testing';
… and here you're not using fakeAsync :)

2018-04-23 08:39 UTC, jjelschen commented on src/lib/src/service/execution/test.execution.service.spec.ts
> +import { ComponentFixture, TestBed, fakeAsync, tick } from '@angular/core/testing';
uses fakeAsync, but never uses tick, so the former is probably unnecessary, as well.

2018-04-23 08:39 UTC, jjelschen commented on src/lib/src/service/execution/test.execution.service.ts
> +  abstract execute(path: string, onThen?: (some: any) => void, onError?: (error: any) => void): void
just if its low-impact: consider renaming "onThen" to "onResponse" (just think the former sounds a bit weird…)

2018-04-23 08:39 UTC, jjelschen commented on src/lib/src/service/execution/test.execution.service.ts
> +            onError?: (error: any) => void): void { // Promise<TestExecutionStatus> {
remove out-commented return type?

2018-04-23 08:39 UTC, jjelschen commented on src/lib/src/service/execution/test.execution.service.ts
> +               onError?: (error: any) => void): void { //  Promise<TestExecutionStatus[]> {
remove out-commented return type?

2018-04-23 08:39 UTC, jjelschen commented on src/lib/src/component/tree-viewer/new-element.component.spec.ts
> +    onSuccess.apply(null, ['some/path']);
is this different from just calling `onSuccess(null, ['some/path'])`?

2018-04-23 09:23 UTC, gunther-bachmann commented on integration/e2e/app.e2e-spec.ts
> +         if (element) { \
true, had to fix some aot setup to make this test work again

2018-04-23 09:23 UTC, gunther-bachmann commented on package.json
> +    "webdriver-manager": "^12.0.6",
merged your branch into this ...

2018-04-24 10:43 UTC, jjelschen approved these changes

2018-04-24 10:44 UTC, merged